package com.rt.ecps.model;

public class Role {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ROLE_ID
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    private String roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ROLE_NAME
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    private String roleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.ROLE_ADDRESS
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    private String roleAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.CREATE_TIME
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ROLE.UPDATE_TIME
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ROLE_ID
     *
     * @return the value of ROLE.ROLE_ID
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ROLE_ID
     *
     * @param roleId the value for ROLE.ROLE_ID
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ROLE_NAME
     *
     * @return the value of ROLE.ROLE_NAME
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ROLE_NAME
     *
     * @param roleName the value for ROLE.ROLE_NAME
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.ROLE_ADDRESS
     *
     * @return the value of ROLE.ROLE_ADDRESS
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    public String getRoleAddress() {
        return roleAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.ROLE_ADDRESS
     *
     * @param roleAddress the value for ROLE.ROLE_ADDRESS
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    public void setRoleAddress(String roleAddress) {
        this.roleAddress = roleAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.CREATE_TIME
     *
     * @return the value of ROLE.CREATE_TIME
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.CREATE_TIME
     *
     * @param createTime the value for ROLE.CREATE_TIME
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ROLE.UPDATE_TIME
     *
     * @return the value of ROLE.UPDATE_TIME
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ROLE.UPDATE_TIME
     *
     * @param updateTime the value for ROLE.UPDATE_TIME
     *
     * @mbggenerated Sun Dec 15 18:18:24 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}