package com.rt.ecps.model;

public class School {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL.SCHOOL_ID
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    private String schoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL.SCHOOL_NAME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    private String schoolName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL.SCHOOL_ADMIN_NAME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    private String schoolAdminName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL.SCHOOL_ADMIN_TELEPHONE
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    private String schoolAdminTelephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL.SCHOOL_ADDRESS
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    private String schoolAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL.STATUS_
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL.CREATE_TIME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SCHOOL.UPDATE_TIME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL.SCHOOL_ID
     *
     * @return the value of SCHOOL.SCHOOL_ID
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public String getSchoolId() {
        return schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL.SCHOOL_ID
     *
     * @param schoolId the value for SCHOOL.SCHOOL_ID
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public void setSchoolId(String schoolId) {
        this.schoolId = schoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL.SCHOOL_NAME
     *
     * @return the value of SCHOOL.SCHOOL_NAME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public String getSchoolName() {
        return schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL.SCHOOL_NAME
     *
     * @param schoolName the value for SCHOOL.SCHOOL_NAME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public void setSchoolName(String schoolName) {
        this.schoolName = schoolName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL.SCHOOL_ADMIN_NAME
     *
     * @return the value of SCHOOL.SCHOOL_ADMIN_NAME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public String getSchoolAdminName() {
        return schoolAdminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL.SCHOOL_ADMIN_NAME
     *
     * @param schoolAdminName the value for SCHOOL.SCHOOL_ADMIN_NAME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public void setSchoolAdminName(String schoolAdminName) {
        this.schoolAdminName = schoolAdminName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL.SCHOOL_ADMIN_TELEPHONE
     *
     * @return the value of SCHOOL.SCHOOL_ADMIN_TELEPHONE
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public String getSchoolAdminTelephone() {
        return schoolAdminTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL.SCHOOL_ADMIN_TELEPHONE
     *
     * @param schoolAdminTelephone the value for SCHOOL.SCHOOL_ADMIN_TELEPHONE
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public void setSchoolAdminTelephone(String schoolAdminTelephone) {
        this.schoolAdminTelephone = schoolAdminTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL.SCHOOL_ADDRESS
     *
     * @return the value of SCHOOL.SCHOOL_ADDRESS
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public String getSchoolAddress() {
        return schoolAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL.SCHOOL_ADDRESS
     *
     * @param schoolAddress the value for SCHOOL.SCHOOL_ADDRESS
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public void setSchoolAddress(String schoolAddress) {
        this.schoolAddress = schoolAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL.STATUS_
     *
     * @return the value of SCHOOL.STATUS_
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL.STATUS_
     *
     * @param status the value for SCHOOL.STATUS_
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL.CREATE_TIME
     *
     * @return the value of SCHOOL.CREATE_TIME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL.CREATE_TIME
     *
     * @param createTime the value for SCHOOL.CREATE_TIME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SCHOOL.UPDATE_TIME
     *
     * @return the value of SCHOOL.UPDATE_TIME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SCHOOL.UPDATE_TIME
     *
     * @param updateTime the value for SCHOOL.UPDATE_TIME
     *
     * @mbggenerated Sun Dec 15 12:56:25 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}