package com.rt.ecps.model;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_.USER_ID
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    private String userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_.LOGIN_NAME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    private String loginName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_.PASSWORD_
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_.USER_NAME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_.TELEPHONE
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_.USER_ADDRESS
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    private String userAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_.STATUS_
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_.CREATE_TIME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    private String createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_.UPDATE_TIME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    private String updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_.USER_ID
     *
     * @return the value of USER_.USER_ID
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_.USER_ID
     *
     * @param userId the value for USER_.USER_ID
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public void setUserId(String userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_.LOGIN_NAME
     *
     * @return the value of USER_.LOGIN_NAME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public String getLoginName() {
        return loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_.LOGIN_NAME
     *
     * @param loginName the value for USER_.LOGIN_NAME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_.PASSWORD_
     *
     * @return the value of USER_.PASSWORD_
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_.PASSWORD_
     *
     * @param password the value for USER_.PASSWORD_
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_.USER_NAME
     *
     * @return the value of USER_.USER_NAME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_.USER_NAME
     *
     * @param userName the value for USER_.USER_NAME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_.TELEPHONE
     *
     * @return the value of USER_.TELEPHONE
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public String getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_.TELEPHONE
     *
     * @param telephone the value for USER_.TELEPHONE
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_.USER_ADDRESS
     *
     * @return the value of USER_.USER_ADDRESS
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public String getUserAddress() {
        return userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_.USER_ADDRESS
     *
     * @param userAddress the value for USER_.USER_ADDRESS
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public void setUserAddress(String userAddress) {
        this.userAddress = userAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_.STATUS_
     *
     * @return the value of USER_.STATUS_
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_.STATUS_
     *
     * @param status the value for USER_.STATUS_
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_.CREATE_TIME
     *
     * @return the value of USER_.CREATE_TIME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public String getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_.CREATE_TIME
     *
     * @param createTime the value for USER_.CREATE_TIME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_.UPDATE_TIME
     *
     * @return the value of USER_.UPDATE_TIME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public String getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_.UPDATE_TIME
     *
     * @param updateTime the value for USER_.UPDATE_TIME
     *
     * @mbggenerated Thu Dec 12 20:10:30 CST 2019
     */
    public void setUpdateTime(String updateTime) {
        this.updateTime = updateTime;
    }
}